// Code generated by ent, DO NOT EDIT.

package contact

import (
	"home-vue-go/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Contact {
	return predicate.Contact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Contact {
	return predicate.Contact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Contact {
	return predicate.Contact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Contact {
	return predicate.Contact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Contact {
	return predicate.Contact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Contact {
	return predicate.Contact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Contact {
	return predicate.Contact(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldType, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldIcon, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldURL, v))
}

// QrCode applies equality check predicate on the "qr_code" field. It's identical to QrCodeEQ.
func QrCode(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldQrCode, v))
}

// HoverColor applies equality check predicate on the "hover_color" field. It's identical to HoverColorEQ.
func HoverColor(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldHoverColor, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldSortOrder, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContainsFold(FieldType, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasSuffix(FieldIcon, v))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContainsFold(FieldIcon, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Contact {
	return predicate.Contact(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Contact {
	return predicate.Contact(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContainsFold(FieldURL, v))
}

// QrCodeEQ applies the EQ predicate on the "qr_code" field.
func QrCodeEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldQrCode, v))
}

// QrCodeNEQ applies the NEQ predicate on the "qr_code" field.
func QrCodeNEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldNEQ(FieldQrCode, v))
}

// QrCodeIn applies the In predicate on the "qr_code" field.
func QrCodeIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldIn(FieldQrCode, vs...))
}

// QrCodeNotIn applies the NotIn predicate on the "qr_code" field.
func QrCodeNotIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldNotIn(FieldQrCode, vs...))
}

// QrCodeGT applies the GT predicate on the "qr_code" field.
func QrCodeGT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGT(FieldQrCode, v))
}

// QrCodeGTE applies the GTE predicate on the "qr_code" field.
func QrCodeGTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGTE(FieldQrCode, v))
}

// QrCodeLT applies the LT predicate on the "qr_code" field.
func QrCodeLT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLT(FieldQrCode, v))
}

// QrCodeLTE applies the LTE predicate on the "qr_code" field.
func QrCodeLTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLTE(FieldQrCode, v))
}

// QrCodeContains applies the Contains predicate on the "qr_code" field.
func QrCodeContains(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContains(FieldQrCode, v))
}

// QrCodeHasPrefix applies the HasPrefix predicate on the "qr_code" field.
func QrCodeHasPrefix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasPrefix(FieldQrCode, v))
}

// QrCodeHasSuffix applies the HasSuffix predicate on the "qr_code" field.
func QrCodeHasSuffix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasSuffix(FieldQrCode, v))
}

// QrCodeIsNil applies the IsNil predicate on the "qr_code" field.
func QrCodeIsNil() predicate.Contact {
	return predicate.Contact(sql.FieldIsNull(FieldQrCode))
}

// QrCodeNotNil applies the NotNil predicate on the "qr_code" field.
func QrCodeNotNil() predicate.Contact {
	return predicate.Contact(sql.FieldNotNull(FieldQrCode))
}

// QrCodeEqualFold applies the EqualFold predicate on the "qr_code" field.
func QrCodeEqualFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEqualFold(FieldQrCode, v))
}

// QrCodeContainsFold applies the ContainsFold predicate on the "qr_code" field.
func QrCodeContainsFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContainsFold(FieldQrCode, v))
}

// HoverColorEQ applies the EQ predicate on the "hover_color" field.
func HoverColorEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldHoverColor, v))
}

// HoverColorNEQ applies the NEQ predicate on the "hover_color" field.
func HoverColorNEQ(v string) predicate.Contact {
	return predicate.Contact(sql.FieldNEQ(FieldHoverColor, v))
}

// HoverColorIn applies the In predicate on the "hover_color" field.
func HoverColorIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldIn(FieldHoverColor, vs...))
}

// HoverColorNotIn applies the NotIn predicate on the "hover_color" field.
func HoverColorNotIn(vs ...string) predicate.Contact {
	return predicate.Contact(sql.FieldNotIn(FieldHoverColor, vs...))
}

// HoverColorGT applies the GT predicate on the "hover_color" field.
func HoverColorGT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGT(FieldHoverColor, v))
}

// HoverColorGTE applies the GTE predicate on the "hover_color" field.
func HoverColorGTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldGTE(FieldHoverColor, v))
}

// HoverColorLT applies the LT predicate on the "hover_color" field.
func HoverColorLT(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLT(FieldHoverColor, v))
}

// HoverColorLTE applies the LTE predicate on the "hover_color" field.
func HoverColorLTE(v string) predicate.Contact {
	return predicate.Contact(sql.FieldLTE(FieldHoverColor, v))
}

// HoverColorContains applies the Contains predicate on the "hover_color" field.
func HoverColorContains(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContains(FieldHoverColor, v))
}

// HoverColorHasPrefix applies the HasPrefix predicate on the "hover_color" field.
func HoverColorHasPrefix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasPrefix(FieldHoverColor, v))
}

// HoverColorHasSuffix applies the HasSuffix predicate on the "hover_color" field.
func HoverColorHasSuffix(v string) predicate.Contact {
	return predicate.Contact(sql.FieldHasSuffix(FieldHoverColor, v))
}

// HoverColorIsNil applies the IsNil predicate on the "hover_color" field.
func HoverColorIsNil() predicate.Contact {
	return predicate.Contact(sql.FieldIsNull(FieldHoverColor))
}

// HoverColorNotNil applies the NotNil predicate on the "hover_color" field.
func HoverColorNotNil() predicate.Contact {
	return predicate.Contact(sql.FieldNotNull(FieldHoverColor))
}

// HoverColorEqualFold applies the EqualFold predicate on the "hover_color" field.
func HoverColorEqualFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldEqualFold(FieldHoverColor, v))
}

// HoverColorContainsFold applies the ContainsFold predicate on the "hover_color" field.
func HoverColorContainsFold(v string) predicate.Contact {
	return predicate.Contact(sql.FieldContainsFold(FieldHoverColor, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Contact {
	return predicate.Contact(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Contact {
	return predicate.Contact(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Contact {
	return predicate.Contact(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Contact {
	return predicate.Contact(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Contact {
	return predicate.Contact(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Contact {
	return predicate.Contact(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Contact {
	return predicate.Contact(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Contact {
	return predicate.Contact(sql.FieldLTE(FieldSortOrder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Contact) predicate.Contact {
	return predicate.Contact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Contact) predicate.Contact {
	return predicate.Contact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Contact) predicate.Contact {
	return predicate.Contact(sql.NotPredicates(p))
}
