// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"home-vue-go/internal/ent/loginhistory"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LoginHistory is the model entity for the LoginHistory schema.
type LoginHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 用户名
	Username string `json:"username,omitempty"`
	// 登录IP地址
	IP string `json:"ip,omitempty"`
	// IP地理位置
	Location string `json:"location,omitempty"`
	// 用户代理
	UserAgent string `json:"user_agent,omitempty"`
	// 登录时间
	LoginTime time.Time `json:"login_time,omitempty"`
	// 登录是否成功
	Success      bool `json:"success,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loginhistory.FieldSuccess:
			values[i] = new(sql.NullBool)
		case loginhistory.FieldID:
			values[i] = new(sql.NullInt64)
		case loginhistory.FieldUsername, loginhistory.FieldIP, loginhistory.FieldLocation, loginhistory.FieldUserAgent:
			values[i] = new(sql.NullString)
		case loginhistory.FieldLoginTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginHistory fields.
func (_m *LoginHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loginhistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case loginhistory.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case loginhistory.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case loginhistory.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = value.String
			}
		case loginhistory.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case loginhistory.FieldLoginTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field login_time", values[i])
			} else if value.Valid {
				_m.LoginTime = value.Time
			}
		case loginhistory.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginHistory.
// This includes values selected through modifiers, order, etc.
func (_m *LoginHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LoginHistory.
// Note that you need to call LoginHistory.Unwrap() before calling this method if this LoginHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LoginHistory) Update() *LoginHistoryUpdateOne {
	return NewLoginHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LoginHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LoginHistory) Unwrap() *LoginHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LoginHistory) String() string {
	var builder strings.Builder
	builder.WriteString("LoginHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(_m.Location)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("login_time=")
	builder.WriteString(_m.LoginTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteByte(')')
	return builder.String()
}

// LoginHistories is a parsable slice of LoginHistory.
type LoginHistories []*LoginHistory
