// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"home-vue-go/internal/ent/loginhistory"
	"home-vue-go/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginHistoryUpdate is the builder for updating LoginHistory entities.
type LoginHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *LoginHistoryMutation
}

// Where appends a list predicates to the LoginHistoryUpdate builder.
func (_u *LoginHistoryUpdate) Where(ps ...predicate.LoginHistory) *LoginHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *LoginHistoryUpdate) SetUsername(v string) *LoginHistoryUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableUsername(v *string) *LoginHistoryUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *LoginHistoryUpdate) SetIP(v string) *LoginHistoryUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableIP(v *string) *LoginHistoryUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *LoginHistoryUpdate) SetLocation(v string) *LoginHistoryUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableLocation(v *string) *LoginHistoryUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *LoginHistoryUpdate) ClearLocation() *LoginHistoryUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginHistoryUpdate) SetUserAgent(v string) *LoginHistoryUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableUserAgent(v *string) *LoginHistoryUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginHistoryUpdate) ClearUserAgent() *LoginHistoryUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetLoginTime sets the "login_time" field.
func (_u *LoginHistoryUpdate) SetLoginTime(v time.Time) *LoginHistoryUpdate {
	_u.mutation.SetLoginTime(v)
	return _u
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableLoginTime(v *time.Time) *LoginHistoryUpdate {
	if v != nil {
		_u.SetLoginTime(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginHistoryUpdate) SetSuccess(v bool) *LoginHistoryUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginHistoryUpdate) SetNillableSuccess(v *bool) *LoginHistoryUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// Mutation returns the LoginHistoryMutation object of the builder.
func (_u *LoginHistoryUpdate) Mutation() *LoginHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LoginHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(loginhistory.Table, loginhistory.Columns, sqlgraph.NewFieldSpec(loginhistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loginhistory.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginhistory.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(loginhistory.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(loginhistory.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginhistory.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginhistory.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.LoginTime(); ok {
		_spec.SetField(loginhistory.FieldLoginTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginhistory.FieldSuccess, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginHistoryUpdateOne is the builder for updating a single LoginHistory entity.
type LoginHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginHistoryMutation
}

// SetUsername sets the "username" field.
func (_u *LoginHistoryUpdateOne) SetUsername(v string) *LoginHistoryUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableUsername(v *string) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *LoginHistoryUpdateOne) SetIP(v string) *LoginHistoryUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableIP(v *string) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *LoginHistoryUpdateOne) SetLocation(v string) *LoginHistoryUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableLocation(v *string) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *LoginHistoryUpdateOne) ClearLocation() *LoginHistoryUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginHistoryUpdateOne) SetUserAgent(v string) *LoginHistoryUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableUserAgent(v *string) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginHistoryUpdateOne) ClearUserAgent() *LoginHistoryUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetLoginTime sets the "login_time" field.
func (_u *LoginHistoryUpdateOne) SetLoginTime(v time.Time) *LoginHistoryUpdateOne {
	_u.mutation.SetLoginTime(v)
	return _u
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableLoginTime(v *time.Time) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetLoginTime(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginHistoryUpdateOne) SetSuccess(v bool) *LoginHistoryUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginHistoryUpdateOne) SetNillableSuccess(v *bool) *LoginHistoryUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// Mutation returns the LoginHistoryMutation object of the builder.
func (_u *LoginHistoryUpdateOne) Mutation() *LoginHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoginHistoryUpdate builder.
func (_u *LoginHistoryUpdateOne) Where(ps ...predicate.LoginHistory) *LoginHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginHistoryUpdateOne) Select(field string, fields ...string) *LoginHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginHistory entity.
func (_u *LoginHistoryUpdateOne) Save(ctx context.Context) (*LoginHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginHistoryUpdateOne) SaveX(ctx context.Context) *LoginHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LoginHistoryUpdateOne) sqlSave(ctx context.Context) (_node *LoginHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(loginhistory.Table, loginhistory.Columns, sqlgraph.NewFieldSpec(loginhistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginhistory.FieldID)
		for _, f := range fields {
			if !loginhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loginhistory.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginhistory.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(loginhistory.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(loginhistory.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginhistory.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginhistory.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.LoginTime(); ok {
		_spec.SetField(loginhistory.FieldLoginTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginhistory.FieldSuccess, field.TypeBool, value)
	}
	_node = &LoginHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
