// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"home-vue-go/internal/ent/loginhistory"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginHistoryCreate is the builder for creating a LoginHistory entity.
type LoginHistoryCreate struct {
	config
	mutation *LoginHistoryMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *LoginHistoryCreate) SetUsername(v string) *LoginHistoryCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *LoginHistoryCreate) SetIP(v string) *LoginHistoryCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetLocation sets the "location" field.
func (_c *LoginHistoryCreate) SetLocation(v string) *LoginHistoryCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *LoginHistoryCreate) SetNillableLocation(v *string) *LoginHistoryCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *LoginHistoryCreate) SetUserAgent(v string) *LoginHistoryCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *LoginHistoryCreate) SetNillableUserAgent(v *string) *LoginHistoryCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetLoginTime sets the "login_time" field.
func (_c *LoginHistoryCreate) SetLoginTime(v time.Time) *LoginHistoryCreate {
	_c.mutation.SetLoginTime(v)
	return _c
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_c *LoginHistoryCreate) SetNillableLoginTime(v *time.Time) *LoginHistoryCreate {
	if v != nil {
		_c.SetLoginTime(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *LoginHistoryCreate) SetSuccess(v bool) *LoginHistoryCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *LoginHistoryCreate) SetNillableSuccess(v *bool) *LoginHistoryCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LoginHistoryCreate) SetID(v int) *LoginHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LoginHistoryMutation object of the builder.
func (_c *LoginHistoryCreate) Mutation() *LoginHistoryMutation {
	return _c.mutation
}

// Save creates the LoginHistory in the database.
func (_c *LoginHistoryCreate) Save(ctx context.Context) (*LoginHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoginHistoryCreate) SaveX(ctx context.Context) *LoginHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoginHistoryCreate) defaults() {
	if _, ok := _c.mutation.LoginTime(); !ok {
		v := loginhistory.DefaultLoginTime()
		_c.mutation.SetLoginTime(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := loginhistory.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoginHistoryCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "LoginHistory.username"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "LoginHistory.ip"`)}
	}
	if _, ok := _c.mutation.LoginTime(); !ok {
		return &ValidationError{Name: "login_time", err: errors.New(`ent: missing required field "LoginHistory.login_time"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "LoginHistory.success"`)}
	}
	return nil
}

func (_c *LoginHistoryCreate) sqlSave(ctx context.Context) (*LoginHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoginHistoryCreate) createSpec() (*LoginHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &LoginHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loginhistory.Table, sqlgraph.NewFieldSpec(loginhistory.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(loginhistory.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(loginhistory.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(loginhistory.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(loginhistory.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.LoginTime(); ok {
		_spec.SetField(loginhistory.FieldLoginTime, field.TypeTime, value)
		_node.LoginTime = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(loginhistory.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	return _node, _spec
}

// LoginHistoryCreateBulk is the builder for creating many LoginHistory entities in bulk.
type LoginHistoryCreateBulk struct {
	config
	err      error
	builders []*LoginHistoryCreate
}

// Save creates the LoginHistory entities in the database.
func (_c *LoginHistoryCreateBulk) Save(ctx context.Context) ([]*LoginHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoginHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoginHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoginHistoryCreateBulk) SaveX(ctx context.Context) []*LoginHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
