// Code generated by ent, DO NOT EDIT.

package ent

import (
	"home-vue-go/internal/ent/contact"
	"home-vue-go/internal/ent/loginhistory"
	"home-vue-go/internal/ent/schema"
	"home-vue-go/internal/ent/site"
	"home-vue-go/internal/ent/siteconfig"
	"home-vue-go/internal/ent/visit"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescSortOrder is the schema descriptor for sort_order field.
	contactDescSortOrder := contactFields[6].Descriptor()
	// contact.DefaultSortOrder holds the default value on creation for the sort_order field.
	contact.DefaultSortOrder = contactDescSortOrder.Default.(int)
	loginhistoryFields := schema.LoginHistory{}.Fields()
	_ = loginhistoryFields
	// loginhistoryDescLoginTime is the schema descriptor for login_time field.
	loginhistoryDescLoginTime := loginhistoryFields[5].Descriptor()
	// loginhistory.DefaultLoginTime holds the default value on creation for the login_time field.
	loginhistory.DefaultLoginTime = loginhistoryDescLoginTime.Default.(func() time.Time)
	// loginhistoryDescSuccess is the schema descriptor for success field.
	loginhistoryDescSuccess := loginhistoryFields[6].Descriptor()
	// loginhistory.DefaultSuccess holds the default value on creation for the success field.
	loginhistory.DefaultSuccess = loginhistoryDescSuccess.Default.(bool)
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescSortOrder is the schema descriptor for sort_order field.
	siteDescSortOrder := siteFields[4].Descriptor()
	// site.DefaultSortOrder holds the default value on creation for the sort_order field.
	site.DefaultSortOrder = siteDescSortOrder.Default.(int)
	siteconfigFields := schema.SiteConfig{}.Fields()
	_ = siteconfigFields
	// siteconfigDescID is the schema descriptor for id field.
	siteconfigDescID := siteconfigFields[0].Descriptor()
	// siteconfig.DefaultID holds the default value on creation for the id field.
	siteconfig.DefaultID = siteconfigDescID.Default.(int)
	visitFields := schema.Visit{}.Fields()
	_ = visitFields
	// visitDescVisitTime is the schema descriptor for visit_time field.
	visitDescVisitTime := visitFields[5].Descriptor()
	// visit.DefaultVisitTime holds the default value on creation for the visit_time field.
	visit.DefaultVisitTime = visitDescVisitTime.Default.(func() time.Time)
}
