// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"home-vue-go/internal/ent/siteconfig"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SiteConfig is the model entity for the SiteConfig schema.
type SiteConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 站点名称
	SiteName string `json:"site_name,omitempty"`
	// 站点URL
	SiteURL string `json:"site_url,omitempty"`
	// 站点图标
	SiteIcon string `json:"site_icon,omitempty"`
	// 站点描述
	SiteDescription string `json:"site_description,omitempty"`
	// 站点关键词
	SiteKeywords string `json:"site_keywords,omitempty"`
	// 用户名
	UserName string `json:"user_name,omitempty"`
	// 头像URL
	ProfileImageURL string `json:"profile_image_url,omitempty"`
	// ICP备案号
	IcpNumber string `json:"icp_number,omitempty"`
	// 公安备案号
	PoliceNumber string `json:"police_number,omitempty"`
	// 网页标题
	PageTitle string `json:"page_title,omitempty"`
	// 网页图标路径
	Favicon string `json:"favicon,omitempty"`
	// Umami统计脚本地址
	UmamiScript string `json:"umami_script,omitempty"`
	// Umami统计网站ID
	UmamiWebsiteID string `json:"umami_website_id,omitempty"`
	// 图标库CDN地址
	IconLibrary string `json:"icon_library,omitempty"`
	// 字体库CDN地址
	FontLibrary  string `json:"font_library,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SiteConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case siteconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case siteconfig.FieldSiteName, siteconfig.FieldSiteURL, siteconfig.FieldSiteIcon, siteconfig.FieldSiteDescription, siteconfig.FieldSiteKeywords, siteconfig.FieldUserName, siteconfig.FieldProfileImageURL, siteconfig.FieldIcpNumber, siteconfig.FieldPoliceNumber, siteconfig.FieldPageTitle, siteconfig.FieldFavicon, siteconfig.FieldUmamiScript, siteconfig.FieldUmamiWebsiteID, siteconfig.FieldIconLibrary, siteconfig.FieldFontLibrary:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SiteConfig fields.
func (_m *SiteConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case siteconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case siteconfig.FieldSiteName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_name", values[i])
			} else if value.Valid {
				_m.SiteName = value.String
			}
		case siteconfig.FieldSiteURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_url", values[i])
			} else if value.Valid {
				_m.SiteURL = value.String
			}
		case siteconfig.FieldSiteIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_icon", values[i])
			} else if value.Valid {
				_m.SiteIcon = value.String
			}
		case siteconfig.FieldSiteDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_description", values[i])
			} else if value.Valid {
				_m.SiteDescription = value.String
			}
		case siteconfig.FieldSiteKeywords:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_keywords", values[i])
			} else if value.Valid {
				_m.SiteKeywords = value.String
			}
		case siteconfig.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case siteconfig.FieldProfileImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_image_url", values[i])
			} else if value.Valid {
				_m.ProfileImageURL = value.String
			}
		case siteconfig.FieldIcpNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icp_number", values[i])
			} else if value.Valid {
				_m.IcpNumber = value.String
			}
		case siteconfig.FieldPoliceNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field police_number", values[i])
			} else if value.Valid {
				_m.PoliceNumber = value.String
			}
		case siteconfig.FieldPageTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field page_title", values[i])
			} else if value.Valid {
				_m.PageTitle = value.String
			}
		case siteconfig.FieldFavicon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field favicon", values[i])
			} else if value.Valid {
				_m.Favicon = value.String
			}
		case siteconfig.FieldUmamiScript:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field umami_script", values[i])
			} else if value.Valid {
				_m.UmamiScript = value.String
			}
		case siteconfig.FieldUmamiWebsiteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field umami_website_id", values[i])
			} else if value.Valid {
				_m.UmamiWebsiteID = value.String
			}
		case siteconfig.FieldIconLibrary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_library", values[i])
			} else if value.Valid {
				_m.IconLibrary = value.String
			}
		case siteconfig.FieldFontLibrary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field font_library", values[i])
			} else if value.Valid {
				_m.FontLibrary = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SiteConfig.
// This includes values selected through modifiers, order, etc.
func (_m *SiteConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SiteConfig.
// Note that you need to call SiteConfig.Unwrap() before calling this method if this SiteConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SiteConfig) Update() *SiteConfigUpdateOne {
	return NewSiteConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SiteConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SiteConfig) Unwrap() *SiteConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SiteConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SiteConfig) String() string {
	var builder strings.Builder
	builder.WriteString("SiteConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("site_name=")
	builder.WriteString(_m.SiteName)
	builder.WriteString(", ")
	builder.WriteString("site_url=")
	builder.WriteString(_m.SiteURL)
	builder.WriteString(", ")
	builder.WriteString("site_icon=")
	builder.WriteString(_m.SiteIcon)
	builder.WriteString(", ")
	builder.WriteString("site_description=")
	builder.WriteString(_m.SiteDescription)
	builder.WriteString(", ")
	builder.WriteString("site_keywords=")
	builder.WriteString(_m.SiteKeywords)
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("profile_image_url=")
	builder.WriteString(_m.ProfileImageURL)
	builder.WriteString(", ")
	builder.WriteString("icp_number=")
	builder.WriteString(_m.IcpNumber)
	builder.WriteString(", ")
	builder.WriteString("police_number=")
	builder.WriteString(_m.PoliceNumber)
	builder.WriteString(", ")
	builder.WriteString("page_title=")
	builder.WriteString(_m.PageTitle)
	builder.WriteString(", ")
	builder.WriteString("favicon=")
	builder.WriteString(_m.Favicon)
	builder.WriteString(", ")
	builder.WriteString("umami_script=")
	builder.WriteString(_m.UmamiScript)
	builder.WriteString(", ")
	builder.WriteString("umami_website_id=")
	builder.WriteString(_m.UmamiWebsiteID)
	builder.WriteString(", ")
	builder.WriteString("icon_library=")
	builder.WriteString(_m.IconLibrary)
	builder.WriteString(", ")
	builder.WriteString("font_library=")
	builder.WriteString(_m.FontLibrary)
	builder.WriteByte(')')
	return builder.String()
}

// SiteConfigs is a parsable slice of SiteConfig.
type SiteConfigs []*SiteConfig
