// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"home-vue-go/internal/ent/visit"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VisitCreate is the builder for creating a Visit entity.
type VisitCreate struct {
	config
	mutation *VisitMutation
	hooks    []Hook
}

// SetPath sets the "path" field.
func (_c *VisitCreate) SetPath(v string) *VisitCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *VisitCreate) SetIP(v string) *VisitCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *VisitCreate) SetUserAgent(v string) *VisitCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *VisitCreate) SetNillableUserAgent(v *string) *VisitCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetReferer sets the "referer" field.
func (_c *VisitCreate) SetReferer(v string) *VisitCreate {
	_c.mutation.SetReferer(v)
	return _c
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_c *VisitCreate) SetNillableReferer(v *string) *VisitCreate {
	if v != nil {
		_c.SetReferer(*v)
	}
	return _c
}

// SetVisitTime sets the "visit_time" field.
func (_c *VisitCreate) SetVisitTime(v time.Time) *VisitCreate {
	_c.mutation.SetVisitTime(v)
	return _c
}

// SetNillableVisitTime sets the "visit_time" field if the given value is not nil.
func (_c *VisitCreate) SetNillableVisitTime(v *time.Time) *VisitCreate {
	if v != nil {
		_c.SetVisitTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VisitCreate) SetID(v int) *VisitCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the VisitMutation object of the builder.
func (_c *VisitCreate) Mutation() *VisitMutation {
	return _c.mutation
}

// Save creates the Visit in the database.
func (_c *VisitCreate) Save(ctx context.Context) (*Visit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VisitCreate) SaveX(ctx context.Context) *Visit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VisitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VisitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VisitCreate) defaults() {
	if _, ok := _c.mutation.VisitTime(); !ok {
		v := visit.DefaultVisitTime()
		_c.mutation.SetVisitTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VisitCreate) check() error {
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Visit.path"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Visit.ip"`)}
	}
	if _, ok := _c.mutation.VisitTime(); !ok {
		return &ValidationError{Name: "visit_time", err: errors.New(`ent: missing required field "Visit.visit_time"`)}
	}
	return nil
}

func (_c *VisitCreate) sqlSave(ctx context.Context) (*Visit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VisitCreate) createSpec() (*Visit, *sqlgraph.CreateSpec) {
	var (
		_node = &Visit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(visit.Table, sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(visit.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(visit.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(visit.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.Referer(); ok {
		_spec.SetField(visit.FieldReferer, field.TypeString, value)
		_node.Referer = value
	}
	if value, ok := _c.mutation.VisitTime(); ok {
		_spec.SetField(visit.FieldVisitTime, field.TypeTime, value)
		_node.VisitTime = value
	}
	return _node, _spec
}

// VisitCreateBulk is the builder for creating many Visit entities in bulk.
type VisitCreateBulk struct {
	config
	err      error
	builders []*VisitCreate
}

// Save creates the Visit entities in the database.
func (_c *VisitCreateBulk) Save(ctx context.Context) ([]*Visit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Visit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VisitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VisitCreateBulk) SaveX(ctx context.Context) []*Visit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VisitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VisitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
