// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// LoginHistory is the predicate function for loginhistory builders.
type LoginHistory func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// SiteConfig is the predicate function for siteconfig builders.
type SiteConfig func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Visit is the predicate function for visit builders.
type Visit func(*sql.Selector)
