// Code generated by ent, DO NOT EDIT.

package siteconfig

import (
	"home-vue-go/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldID, id))
}

// SiteName applies equality check predicate on the "site_name" field. It's identical to SiteNameEQ.
func SiteName(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteName, v))
}

// SiteURL applies equality check predicate on the "site_url" field. It's identical to SiteURLEQ.
func SiteURL(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteURL, v))
}

// SiteIcon applies equality check predicate on the "site_icon" field. It's identical to SiteIconEQ.
func SiteIcon(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteIcon, v))
}

// SiteDescription applies equality check predicate on the "site_description" field. It's identical to SiteDescriptionEQ.
func SiteDescription(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteDescription, v))
}

// SiteKeywords applies equality check predicate on the "site_keywords" field. It's identical to SiteKeywordsEQ.
func SiteKeywords(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteKeywords, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldUserName, v))
}

// ProfileImageURL applies equality check predicate on the "profile_image_url" field. It's identical to ProfileImageURLEQ.
func ProfileImageURL(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldProfileImageURL, v))
}

// IcpNumber applies equality check predicate on the "icp_number" field. It's identical to IcpNumberEQ.
func IcpNumber(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldIcpNumber, v))
}

// PoliceNumber applies equality check predicate on the "police_number" field. It's identical to PoliceNumberEQ.
func PoliceNumber(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldPoliceNumber, v))
}

// PageTitle applies equality check predicate on the "page_title" field. It's identical to PageTitleEQ.
func PageTitle(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldPageTitle, v))
}

// Favicon applies equality check predicate on the "favicon" field. It's identical to FaviconEQ.
func Favicon(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldFavicon, v))
}

// UmamiScript applies equality check predicate on the "umami_script" field. It's identical to UmamiScriptEQ.
func UmamiScript(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldUmamiScript, v))
}

// UmamiWebsiteID applies equality check predicate on the "umami_website_id" field. It's identical to UmamiWebsiteIDEQ.
func UmamiWebsiteID(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldUmamiWebsiteID, v))
}

// IconLibrary applies equality check predicate on the "icon_library" field. It's identical to IconLibraryEQ.
func IconLibrary(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldIconLibrary, v))
}

// FontLibrary applies equality check predicate on the "font_library" field. It's identical to FontLibraryEQ.
func FontLibrary(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldFontLibrary, v))
}

// SiteNameEQ applies the EQ predicate on the "site_name" field.
func SiteNameEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteName, v))
}

// SiteNameNEQ applies the NEQ predicate on the "site_name" field.
func SiteNameNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldSiteName, v))
}

// SiteNameIn applies the In predicate on the "site_name" field.
func SiteNameIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldSiteName, vs...))
}

// SiteNameNotIn applies the NotIn predicate on the "site_name" field.
func SiteNameNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldSiteName, vs...))
}

// SiteNameGT applies the GT predicate on the "site_name" field.
func SiteNameGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldSiteName, v))
}

// SiteNameGTE applies the GTE predicate on the "site_name" field.
func SiteNameGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldSiteName, v))
}

// SiteNameLT applies the LT predicate on the "site_name" field.
func SiteNameLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldSiteName, v))
}

// SiteNameLTE applies the LTE predicate on the "site_name" field.
func SiteNameLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldSiteName, v))
}

// SiteNameContains applies the Contains predicate on the "site_name" field.
func SiteNameContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldSiteName, v))
}

// SiteNameHasPrefix applies the HasPrefix predicate on the "site_name" field.
func SiteNameHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldSiteName, v))
}

// SiteNameHasSuffix applies the HasSuffix predicate on the "site_name" field.
func SiteNameHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldSiteName, v))
}

// SiteNameEqualFold applies the EqualFold predicate on the "site_name" field.
func SiteNameEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldSiteName, v))
}

// SiteNameContainsFold applies the ContainsFold predicate on the "site_name" field.
func SiteNameContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldSiteName, v))
}

// SiteURLEQ applies the EQ predicate on the "site_url" field.
func SiteURLEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteURL, v))
}

// SiteURLNEQ applies the NEQ predicate on the "site_url" field.
func SiteURLNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldSiteURL, v))
}

// SiteURLIn applies the In predicate on the "site_url" field.
func SiteURLIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldSiteURL, vs...))
}

// SiteURLNotIn applies the NotIn predicate on the "site_url" field.
func SiteURLNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldSiteURL, vs...))
}

// SiteURLGT applies the GT predicate on the "site_url" field.
func SiteURLGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldSiteURL, v))
}

// SiteURLGTE applies the GTE predicate on the "site_url" field.
func SiteURLGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldSiteURL, v))
}

// SiteURLLT applies the LT predicate on the "site_url" field.
func SiteURLLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldSiteURL, v))
}

// SiteURLLTE applies the LTE predicate on the "site_url" field.
func SiteURLLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldSiteURL, v))
}

// SiteURLContains applies the Contains predicate on the "site_url" field.
func SiteURLContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldSiteURL, v))
}

// SiteURLHasPrefix applies the HasPrefix predicate on the "site_url" field.
func SiteURLHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldSiteURL, v))
}

// SiteURLHasSuffix applies the HasSuffix predicate on the "site_url" field.
func SiteURLHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldSiteURL, v))
}

// SiteURLEqualFold applies the EqualFold predicate on the "site_url" field.
func SiteURLEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldSiteURL, v))
}

// SiteURLContainsFold applies the ContainsFold predicate on the "site_url" field.
func SiteURLContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldSiteURL, v))
}

// SiteIconEQ applies the EQ predicate on the "site_icon" field.
func SiteIconEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteIcon, v))
}

// SiteIconNEQ applies the NEQ predicate on the "site_icon" field.
func SiteIconNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldSiteIcon, v))
}

// SiteIconIn applies the In predicate on the "site_icon" field.
func SiteIconIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldSiteIcon, vs...))
}

// SiteIconNotIn applies the NotIn predicate on the "site_icon" field.
func SiteIconNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldSiteIcon, vs...))
}

// SiteIconGT applies the GT predicate on the "site_icon" field.
func SiteIconGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldSiteIcon, v))
}

// SiteIconGTE applies the GTE predicate on the "site_icon" field.
func SiteIconGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldSiteIcon, v))
}

// SiteIconLT applies the LT predicate on the "site_icon" field.
func SiteIconLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldSiteIcon, v))
}

// SiteIconLTE applies the LTE predicate on the "site_icon" field.
func SiteIconLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldSiteIcon, v))
}

// SiteIconContains applies the Contains predicate on the "site_icon" field.
func SiteIconContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldSiteIcon, v))
}

// SiteIconHasPrefix applies the HasPrefix predicate on the "site_icon" field.
func SiteIconHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldSiteIcon, v))
}

// SiteIconHasSuffix applies the HasSuffix predicate on the "site_icon" field.
func SiteIconHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldSiteIcon, v))
}

// SiteIconEqualFold applies the EqualFold predicate on the "site_icon" field.
func SiteIconEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldSiteIcon, v))
}

// SiteIconContainsFold applies the ContainsFold predicate on the "site_icon" field.
func SiteIconContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldSiteIcon, v))
}

// SiteDescriptionEQ applies the EQ predicate on the "site_description" field.
func SiteDescriptionEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteDescription, v))
}

// SiteDescriptionNEQ applies the NEQ predicate on the "site_description" field.
func SiteDescriptionNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldSiteDescription, v))
}

// SiteDescriptionIn applies the In predicate on the "site_description" field.
func SiteDescriptionIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldSiteDescription, vs...))
}

// SiteDescriptionNotIn applies the NotIn predicate on the "site_description" field.
func SiteDescriptionNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldSiteDescription, vs...))
}

// SiteDescriptionGT applies the GT predicate on the "site_description" field.
func SiteDescriptionGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldSiteDescription, v))
}

// SiteDescriptionGTE applies the GTE predicate on the "site_description" field.
func SiteDescriptionGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldSiteDescription, v))
}

// SiteDescriptionLT applies the LT predicate on the "site_description" field.
func SiteDescriptionLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldSiteDescription, v))
}

// SiteDescriptionLTE applies the LTE predicate on the "site_description" field.
func SiteDescriptionLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldSiteDescription, v))
}

// SiteDescriptionContains applies the Contains predicate on the "site_description" field.
func SiteDescriptionContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldSiteDescription, v))
}

// SiteDescriptionHasPrefix applies the HasPrefix predicate on the "site_description" field.
func SiteDescriptionHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldSiteDescription, v))
}

// SiteDescriptionHasSuffix applies the HasSuffix predicate on the "site_description" field.
func SiteDescriptionHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldSiteDescription, v))
}

// SiteDescriptionEqualFold applies the EqualFold predicate on the "site_description" field.
func SiteDescriptionEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldSiteDescription, v))
}

// SiteDescriptionContainsFold applies the ContainsFold predicate on the "site_description" field.
func SiteDescriptionContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldSiteDescription, v))
}

// SiteKeywordsEQ applies the EQ predicate on the "site_keywords" field.
func SiteKeywordsEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldSiteKeywords, v))
}

// SiteKeywordsNEQ applies the NEQ predicate on the "site_keywords" field.
func SiteKeywordsNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldSiteKeywords, v))
}

// SiteKeywordsIn applies the In predicate on the "site_keywords" field.
func SiteKeywordsIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldSiteKeywords, vs...))
}

// SiteKeywordsNotIn applies the NotIn predicate on the "site_keywords" field.
func SiteKeywordsNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldSiteKeywords, vs...))
}

// SiteKeywordsGT applies the GT predicate on the "site_keywords" field.
func SiteKeywordsGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldSiteKeywords, v))
}

// SiteKeywordsGTE applies the GTE predicate on the "site_keywords" field.
func SiteKeywordsGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldSiteKeywords, v))
}

// SiteKeywordsLT applies the LT predicate on the "site_keywords" field.
func SiteKeywordsLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldSiteKeywords, v))
}

// SiteKeywordsLTE applies the LTE predicate on the "site_keywords" field.
func SiteKeywordsLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldSiteKeywords, v))
}

// SiteKeywordsContains applies the Contains predicate on the "site_keywords" field.
func SiteKeywordsContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldSiteKeywords, v))
}

// SiteKeywordsHasPrefix applies the HasPrefix predicate on the "site_keywords" field.
func SiteKeywordsHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldSiteKeywords, v))
}

// SiteKeywordsHasSuffix applies the HasSuffix predicate on the "site_keywords" field.
func SiteKeywordsHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldSiteKeywords, v))
}

// SiteKeywordsEqualFold applies the EqualFold predicate on the "site_keywords" field.
func SiteKeywordsEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldSiteKeywords, v))
}

// SiteKeywordsContainsFold applies the ContainsFold predicate on the "site_keywords" field.
func SiteKeywordsContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldSiteKeywords, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldUserName, v))
}

// ProfileImageURLEQ applies the EQ predicate on the "profile_image_url" field.
func ProfileImageURLEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldProfileImageURL, v))
}

// ProfileImageURLNEQ applies the NEQ predicate on the "profile_image_url" field.
func ProfileImageURLNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldProfileImageURL, v))
}

// ProfileImageURLIn applies the In predicate on the "profile_image_url" field.
func ProfileImageURLIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldProfileImageURL, vs...))
}

// ProfileImageURLNotIn applies the NotIn predicate on the "profile_image_url" field.
func ProfileImageURLNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldProfileImageURL, vs...))
}

// ProfileImageURLGT applies the GT predicate on the "profile_image_url" field.
func ProfileImageURLGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldProfileImageURL, v))
}

// ProfileImageURLGTE applies the GTE predicate on the "profile_image_url" field.
func ProfileImageURLGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldProfileImageURL, v))
}

// ProfileImageURLLT applies the LT predicate on the "profile_image_url" field.
func ProfileImageURLLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldProfileImageURL, v))
}

// ProfileImageURLLTE applies the LTE predicate on the "profile_image_url" field.
func ProfileImageURLLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldProfileImageURL, v))
}

// ProfileImageURLContains applies the Contains predicate on the "profile_image_url" field.
func ProfileImageURLContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldProfileImageURL, v))
}

// ProfileImageURLHasPrefix applies the HasPrefix predicate on the "profile_image_url" field.
func ProfileImageURLHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldProfileImageURL, v))
}

// ProfileImageURLHasSuffix applies the HasSuffix predicate on the "profile_image_url" field.
func ProfileImageURLHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldProfileImageURL, v))
}

// ProfileImageURLIsNil applies the IsNil predicate on the "profile_image_url" field.
func ProfileImageURLIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldProfileImageURL))
}

// ProfileImageURLNotNil applies the NotNil predicate on the "profile_image_url" field.
func ProfileImageURLNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldProfileImageURL))
}

// ProfileImageURLEqualFold applies the EqualFold predicate on the "profile_image_url" field.
func ProfileImageURLEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldProfileImageURL, v))
}

// ProfileImageURLContainsFold applies the ContainsFold predicate on the "profile_image_url" field.
func ProfileImageURLContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldProfileImageURL, v))
}

// IcpNumberEQ applies the EQ predicate on the "icp_number" field.
func IcpNumberEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldIcpNumber, v))
}

// IcpNumberNEQ applies the NEQ predicate on the "icp_number" field.
func IcpNumberNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldIcpNumber, v))
}

// IcpNumberIn applies the In predicate on the "icp_number" field.
func IcpNumberIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldIcpNumber, vs...))
}

// IcpNumberNotIn applies the NotIn predicate on the "icp_number" field.
func IcpNumberNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldIcpNumber, vs...))
}

// IcpNumberGT applies the GT predicate on the "icp_number" field.
func IcpNumberGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldIcpNumber, v))
}

// IcpNumberGTE applies the GTE predicate on the "icp_number" field.
func IcpNumberGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldIcpNumber, v))
}

// IcpNumberLT applies the LT predicate on the "icp_number" field.
func IcpNumberLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldIcpNumber, v))
}

// IcpNumberLTE applies the LTE predicate on the "icp_number" field.
func IcpNumberLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldIcpNumber, v))
}

// IcpNumberContains applies the Contains predicate on the "icp_number" field.
func IcpNumberContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldIcpNumber, v))
}

// IcpNumberHasPrefix applies the HasPrefix predicate on the "icp_number" field.
func IcpNumberHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldIcpNumber, v))
}

// IcpNumberHasSuffix applies the HasSuffix predicate on the "icp_number" field.
func IcpNumberHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldIcpNumber, v))
}

// IcpNumberIsNil applies the IsNil predicate on the "icp_number" field.
func IcpNumberIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldIcpNumber))
}

// IcpNumberNotNil applies the NotNil predicate on the "icp_number" field.
func IcpNumberNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldIcpNumber))
}

// IcpNumberEqualFold applies the EqualFold predicate on the "icp_number" field.
func IcpNumberEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldIcpNumber, v))
}

// IcpNumberContainsFold applies the ContainsFold predicate on the "icp_number" field.
func IcpNumberContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldIcpNumber, v))
}

// PoliceNumberEQ applies the EQ predicate on the "police_number" field.
func PoliceNumberEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldPoliceNumber, v))
}

// PoliceNumberNEQ applies the NEQ predicate on the "police_number" field.
func PoliceNumberNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldPoliceNumber, v))
}

// PoliceNumberIn applies the In predicate on the "police_number" field.
func PoliceNumberIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldPoliceNumber, vs...))
}

// PoliceNumberNotIn applies the NotIn predicate on the "police_number" field.
func PoliceNumberNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldPoliceNumber, vs...))
}

// PoliceNumberGT applies the GT predicate on the "police_number" field.
func PoliceNumberGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldPoliceNumber, v))
}

// PoliceNumberGTE applies the GTE predicate on the "police_number" field.
func PoliceNumberGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldPoliceNumber, v))
}

// PoliceNumberLT applies the LT predicate on the "police_number" field.
func PoliceNumberLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldPoliceNumber, v))
}

// PoliceNumberLTE applies the LTE predicate on the "police_number" field.
func PoliceNumberLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldPoliceNumber, v))
}

// PoliceNumberContains applies the Contains predicate on the "police_number" field.
func PoliceNumberContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldPoliceNumber, v))
}

// PoliceNumberHasPrefix applies the HasPrefix predicate on the "police_number" field.
func PoliceNumberHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldPoliceNumber, v))
}

// PoliceNumberHasSuffix applies the HasSuffix predicate on the "police_number" field.
func PoliceNumberHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldPoliceNumber, v))
}

// PoliceNumberIsNil applies the IsNil predicate on the "police_number" field.
func PoliceNumberIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldPoliceNumber))
}

// PoliceNumberNotNil applies the NotNil predicate on the "police_number" field.
func PoliceNumberNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldPoliceNumber))
}

// PoliceNumberEqualFold applies the EqualFold predicate on the "police_number" field.
func PoliceNumberEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldPoliceNumber, v))
}

// PoliceNumberContainsFold applies the ContainsFold predicate on the "police_number" field.
func PoliceNumberContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldPoliceNumber, v))
}

// PageTitleEQ applies the EQ predicate on the "page_title" field.
func PageTitleEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldPageTitle, v))
}

// PageTitleNEQ applies the NEQ predicate on the "page_title" field.
func PageTitleNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldPageTitle, v))
}

// PageTitleIn applies the In predicate on the "page_title" field.
func PageTitleIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldPageTitle, vs...))
}

// PageTitleNotIn applies the NotIn predicate on the "page_title" field.
func PageTitleNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldPageTitle, vs...))
}

// PageTitleGT applies the GT predicate on the "page_title" field.
func PageTitleGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldPageTitle, v))
}

// PageTitleGTE applies the GTE predicate on the "page_title" field.
func PageTitleGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldPageTitle, v))
}

// PageTitleLT applies the LT predicate on the "page_title" field.
func PageTitleLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldPageTitle, v))
}

// PageTitleLTE applies the LTE predicate on the "page_title" field.
func PageTitleLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldPageTitle, v))
}

// PageTitleContains applies the Contains predicate on the "page_title" field.
func PageTitleContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldPageTitle, v))
}

// PageTitleHasPrefix applies the HasPrefix predicate on the "page_title" field.
func PageTitleHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldPageTitle, v))
}

// PageTitleHasSuffix applies the HasSuffix predicate on the "page_title" field.
func PageTitleHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldPageTitle, v))
}

// PageTitleIsNil applies the IsNil predicate on the "page_title" field.
func PageTitleIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldPageTitle))
}

// PageTitleNotNil applies the NotNil predicate on the "page_title" field.
func PageTitleNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldPageTitle))
}

// PageTitleEqualFold applies the EqualFold predicate on the "page_title" field.
func PageTitleEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldPageTitle, v))
}

// PageTitleContainsFold applies the ContainsFold predicate on the "page_title" field.
func PageTitleContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldPageTitle, v))
}

// FaviconEQ applies the EQ predicate on the "favicon" field.
func FaviconEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldFavicon, v))
}

// FaviconNEQ applies the NEQ predicate on the "favicon" field.
func FaviconNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldFavicon, v))
}

// FaviconIn applies the In predicate on the "favicon" field.
func FaviconIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldFavicon, vs...))
}

// FaviconNotIn applies the NotIn predicate on the "favicon" field.
func FaviconNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldFavicon, vs...))
}

// FaviconGT applies the GT predicate on the "favicon" field.
func FaviconGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldFavicon, v))
}

// FaviconGTE applies the GTE predicate on the "favicon" field.
func FaviconGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldFavicon, v))
}

// FaviconLT applies the LT predicate on the "favicon" field.
func FaviconLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldFavicon, v))
}

// FaviconLTE applies the LTE predicate on the "favicon" field.
func FaviconLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldFavicon, v))
}

// FaviconContains applies the Contains predicate on the "favicon" field.
func FaviconContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldFavicon, v))
}

// FaviconHasPrefix applies the HasPrefix predicate on the "favicon" field.
func FaviconHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldFavicon, v))
}

// FaviconHasSuffix applies the HasSuffix predicate on the "favicon" field.
func FaviconHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldFavicon, v))
}

// FaviconIsNil applies the IsNil predicate on the "favicon" field.
func FaviconIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldFavicon))
}

// FaviconNotNil applies the NotNil predicate on the "favicon" field.
func FaviconNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldFavicon))
}

// FaviconEqualFold applies the EqualFold predicate on the "favicon" field.
func FaviconEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldFavicon, v))
}

// FaviconContainsFold applies the ContainsFold predicate on the "favicon" field.
func FaviconContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldFavicon, v))
}

// UmamiScriptEQ applies the EQ predicate on the "umami_script" field.
func UmamiScriptEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldUmamiScript, v))
}

// UmamiScriptNEQ applies the NEQ predicate on the "umami_script" field.
func UmamiScriptNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldUmamiScript, v))
}

// UmamiScriptIn applies the In predicate on the "umami_script" field.
func UmamiScriptIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldUmamiScript, vs...))
}

// UmamiScriptNotIn applies the NotIn predicate on the "umami_script" field.
func UmamiScriptNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldUmamiScript, vs...))
}

// UmamiScriptGT applies the GT predicate on the "umami_script" field.
func UmamiScriptGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldUmamiScript, v))
}

// UmamiScriptGTE applies the GTE predicate on the "umami_script" field.
func UmamiScriptGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldUmamiScript, v))
}

// UmamiScriptLT applies the LT predicate on the "umami_script" field.
func UmamiScriptLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldUmamiScript, v))
}

// UmamiScriptLTE applies the LTE predicate on the "umami_script" field.
func UmamiScriptLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldUmamiScript, v))
}

// UmamiScriptContains applies the Contains predicate on the "umami_script" field.
func UmamiScriptContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldUmamiScript, v))
}

// UmamiScriptHasPrefix applies the HasPrefix predicate on the "umami_script" field.
func UmamiScriptHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldUmamiScript, v))
}

// UmamiScriptHasSuffix applies the HasSuffix predicate on the "umami_script" field.
func UmamiScriptHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldUmamiScript, v))
}

// UmamiScriptIsNil applies the IsNil predicate on the "umami_script" field.
func UmamiScriptIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldUmamiScript))
}

// UmamiScriptNotNil applies the NotNil predicate on the "umami_script" field.
func UmamiScriptNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldUmamiScript))
}

// UmamiScriptEqualFold applies the EqualFold predicate on the "umami_script" field.
func UmamiScriptEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldUmamiScript, v))
}

// UmamiScriptContainsFold applies the ContainsFold predicate on the "umami_script" field.
func UmamiScriptContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldUmamiScript, v))
}

// UmamiWebsiteIDEQ applies the EQ predicate on the "umami_website_id" field.
func UmamiWebsiteIDEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDNEQ applies the NEQ predicate on the "umami_website_id" field.
func UmamiWebsiteIDNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDIn applies the In predicate on the "umami_website_id" field.
func UmamiWebsiteIDIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldUmamiWebsiteID, vs...))
}

// UmamiWebsiteIDNotIn applies the NotIn predicate on the "umami_website_id" field.
func UmamiWebsiteIDNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldUmamiWebsiteID, vs...))
}

// UmamiWebsiteIDGT applies the GT predicate on the "umami_website_id" field.
func UmamiWebsiteIDGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDGTE applies the GTE predicate on the "umami_website_id" field.
func UmamiWebsiteIDGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDLT applies the LT predicate on the "umami_website_id" field.
func UmamiWebsiteIDLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDLTE applies the LTE predicate on the "umami_website_id" field.
func UmamiWebsiteIDLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDContains applies the Contains predicate on the "umami_website_id" field.
func UmamiWebsiteIDContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDHasPrefix applies the HasPrefix predicate on the "umami_website_id" field.
func UmamiWebsiteIDHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDHasSuffix applies the HasSuffix predicate on the "umami_website_id" field.
func UmamiWebsiteIDHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDIsNil applies the IsNil predicate on the "umami_website_id" field.
func UmamiWebsiteIDIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldUmamiWebsiteID))
}

// UmamiWebsiteIDNotNil applies the NotNil predicate on the "umami_website_id" field.
func UmamiWebsiteIDNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldUmamiWebsiteID))
}

// UmamiWebsiteIDEqualFold applies the EqualFold predicate on the "umami_website_id" field.
func UmamiWebsiteIDEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldUmamiWebsiteID, v))
}

// UmamiWebsiteIDContainsFold applies the ContainsFold predicate on the "umami_website_id" field.
func UmamiWebsiteIDContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldUmamiWebsiteID, v))
}

// IconLibraryEQ applies the EQ predicate on the "icon_library" field.
func IconLibraryEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldIconLibrary, v))
}

// IconLibraryNEQ applies the NEQ predicate on the "icon_library" field.
func IconLibraryNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldIconLibrary, v))
}

// IconLibraryIn applies the In predicate on the "icon_library" field.
func IconLibraryIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldIconLibrary, vs...))
}

// IconLibraryNotIn applies the NotIn predicate on the "icon_library" field.
func IconLibraryNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldIconLibrary, vs...))
}

// IconLibraryGT applies the GT predicate on the "icon_library" field.
func IconLibraryGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldIconLibrary, v))
}

// IconLibraryGTE applies the GTE predicate on the "icon_library" field.
func IconLibraryGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldIconLibrary, v))
}

// IconLibraryLT applies the LT predicate on the "icon_library" field.
func IconLibraryLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldIconLibrary, v))
}

// IconLibraryLTE applies the LTE predicate on the "icon_library" field.
func IconLibraryLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldIconLibrary, v))
}

// IconLibraryContains applies the Contains predicate on the "icon_library" field.
func IconLibraryContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldIconLibrary, v))
}

// IconLibraryHasPrefix applies the HasPrefix predicate on the "icon_library" field.
func IconLibraryHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldIconLibrary, v))
}

// IconLibraryHasSuffix applies the HasSuffix predicate on the "icon_library" field.
func IconLibraryHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldIconLibrary, v))
}

// IconLibraryIsNil applies the IsNil predicate on the "icon_library" field.
func IconLibraryIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldIconLibrary))
}

// IconLibraryNotNil applies the NotNil predicate on the "icon_library" field.
func IconLibraryNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldIconLibrary))
}

// IconLibraryEqualFold applies the EqualFold predicate on the "icon_library" field.
func IconLibraryEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldIconLibrary, v))
}

// IconLibraryContainsFold applies the ContainsFold predicate on the "icon_library" field.
func IconLibraryContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldIconLibrary, v))
}

// FontLibraryEQ applies the EQ predicate on the "font_library" field.
func FontLibraryEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEQ(FieldFontLibrary, v))
}

// FontLibraryNEQ applies the NEQ predicate on the "font_library" field.
func FontLibraryNEQ(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNEQ(FieldFontLibrary, v))
}

// FontLibraryIn applies the In predicate on the "font_library" field.
func FontLibraryIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIn(FieldFontLibrary, vs...))
}

// FontLibraryNotIn applies the NotIn predicate on the "font_library" field.
func FontLibraryNotIn(vs ...string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotIn(FieldFontLibrary, vs...))
}

// FontLibraryGT applies the GT predicate on the "font_library" field.
func FontLibraryGT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGT(FieldFontLibrary, v))
}

// FontLibraryGTE applies the GTE predicate on the "font_library" field.
func FontLibraryGTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldGTE(FieldFontLibrary, v))
}

// FontLibraryLT applies the LT predicate on the "font_library" field.
func FontLibraryLT(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLT(FieldFontLibrary, v))
}

// FontLibraryLTE applies the LTE predicate on the "font_library" field.
func FontLibraryLTE(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldLTE(FieldFontLibrary, v))
}

// FontLibraryContains applies the Contains predicate on the "font_library" field.
func FontLibraryContains(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContains(FieldFontLibrary, v))
}

// FontLibraryHasPrefix applies the HasPrefix predicate on the "font_library" field.
func FontLibraryHasPrefix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasPrefix(FieldFontLibrary, v))
}

// FontLibraryHasSuffix applies the HasSuffix predicate on the "font_library" field.
func FontLibraryHasSuffix(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldHasSuffix(FieldFontLibrary, v))
}

// FontLibraryIsNil applies the IsNil predicate on the "font_library" field.
func FontLibraryIsNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldIsNull(FieldFontLibrary))
}

// FontLibraryNotNil applies the NotNil predicate on the "font_library" field.
func FontLibraryNotNil() predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldNotNull(FieldFontLibrary))
}

// FontLibraryEqualFold applies the EqualFold predicate on the "font_library" field.
func FontLibraryEqualFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldEqualFold(FieldFontLibrary, v))
}

// FontLibraryContainsFold applies the ContainsFold predicate on the "font_library" field.
func FontLibraryContainsFold(v string) predicate.SiteConfig {
	return predicate.SiteConfig(sql.FieldContainsFold(FieldFontLibrary, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SiteConfig) predicate.SiteConfig {
	return predicate.SiteConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SiteConfig) predicate.SiteConfig {
	return predicate.SiteConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SiteConfig) predicate.SiteConfig {
	return predicate.SiteConfig(sql.NotPredicates(p))
}
